spring:

  #    kafka配置信息
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entry?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    redis:
      lettuce:
      pool:
        max-wait: 100
        max-active: 200
        max-idle: 10
        min-idle: -1
      host: localhost
      port: 6379
      password:
      timeout: 1000
server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    return-instance-for-empty-row: true
logging:
  level:
    org:
      springframework:
        web: ERROR
    com:
      yiibai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#    /shiro
authc:
  loginUrl: /login    #用户登录的地址
roles:
  unauthorizedUrl: /login #用户没有对应角色的跳转重指向
logout:
  redirectUrl: /login #用户没有对应权限的跳转重指向


