package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Clock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.cl_id
     *
     * @mbg.generated
     */
    private Integer clId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.cl_title
     *
     * @mbg.generated
     */
    private String clTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.cl_place
     *
     * @mbg.generated
     */
    private String clPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.cl_content
     *
     * @mbg.generated
     */
    private String clContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.cl_state
     *
     * @mbg.generated
     */
    private Integer clState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.circulation
     *
     * @mbg.generated
     */
    private Integer circulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.cl_id
     *
     * @return the value of clock.cl_id
     *
     * @mbg.generated
     */
    public Integer getClId() {
        return clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.cl_id
     *
     * @param clId the value for clock.cl_id
     *
     * @mbg.generated
     */
    public void setClId(Integer clId) {
        this.clId = clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.cl_title
     *
     * @return the value of clock.cl_title
     *
     * @mbg.generated
     */
    public String getClTitle() {
        return clTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.cl_title
     *
     * @param clTitle the value for clock.cl_title
     *
     * @mbg.generated
     */
    public void setClTitle(String clTitle) {
        this.clTitle = clTitle == null ? null : clTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.cl_place
     *
     * @return the value of clock.cl_place
     *
     * @mbg.generated
     */
    public String getClPlace() {
        return clPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.cl_place
     *
     * @param clPlace the value for clock.cl_place
     *
     * @mbg.generated
     */
    public void setClPlace(String clPlace) {
        this.clPlace = clPlace == null ? null : clPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.cl_content
     *
     * @return the value of clock.cl_content
     *
     * @mbg.generated
     */
    public String getClContent() {
        return clContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.cl_content
     *
     * @param clContent the value for clock.cl_content
     *
     * @mbg.generated
     */
    public void setClContent(String clContent) {
        this.clContent = clContent == null ? null : clContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.createtime
     *
     * @return the value of clock.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.createtime
     *
     * @param createtime the value for clock.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.cl_state
     *
     * @return the value of clock.cl_state
     *
     * @mbg.generated
     */
    public Integer getClState() {
        return clState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.cl_state
     *
     * @param clState the value for clock.cl_state
     *
     * @mbg.generated
     */
    public void setClState(Integer clState) {
        this.clState = clState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.circulation
     *
     * @return the value of clock.circulation
     *
     * @mbg.generated
     */
    public Integer getCirculation() {
        return circulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.circulation
     *
     * @param circulation the value for clock.circulation
     *
     * @mbg.generated
     */
    public void setCirculation(Integer circulation) {
        this.circulation = circulation;
    }
}