package com.cn.exclusiveGirlfriend.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public ClockExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clock
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClIdIsNull() {
            addCriterion("cl_id is null");
            return (Criteria) this;
        }

        public Criteria andClIdIsNotNull() {
            addCriterion("cl_id is not null");
            return (Criteria) this;
        }

        public Criteria andClIdEqualTo(Integer value) {
            addCriterion("cl_id =", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotEqualTo(Integer value) {
            addCriterion("cl_id <>", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThan(Integer value) {
            addCriterion("cl_id >", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cl_id >=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThan(Integer value) {
            addCriterion("cl_id <", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThanOrEqualTo(Integer value) {
            addCriterion("cl_id <=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdIn(List<Integer> values) {
            addCriterion("cl_id in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotIn(List<Integer> values) {
            addCriterion("cl_id not in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdBetween(Integer value1, Integer value2) {
            addCriterion("cl_id between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cl_id not between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClTitleIsNull() {
            addCriterion("cl_title is null");
            return (Criteria) this;
        }

        public Criteria andClTitleIsNotNull() {
            addCriterion("cl_title is not null");
            return (Criteria) this;
        }

        public Criteria andClTitleEqualTo(String value) {
            addCriterion("cl_title =", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotEqualTo(String value) {
            addCriterion("cl_title <>", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleGreaterThan(String value) {
            addCriterion("cl_title >", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleGreaterThanOrEqualTo(String value) {
            addCriterion("cl_title >=", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleLessThan(String value) {
            addCriterion("cl_title <", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleLessThanOrEqualTo(String value) {
            addCriterion("cl_title <=", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleLike(String value) {
            addCriterion("cl_title like", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotLike(String value) {
            addCriterion("cl_title not like", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleIn(List<String> values) {
            addCriterion("cl_title in", values, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotIn(List<String> values) {
            addCriterion("cl_title not in", values, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleBetween(String value1, String value2) {
            addCriterion("cl_title between", value1, value2, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotBetween(String value1, String value2) {
            addCriterion("cl_title not between", value1, value2, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClPlaceIsNull() {
            addCriterion("cl_place is null");
            return (Criteria) this;
        }

        public Criteria andClPlaceIsNotNull() {
            addCriterion("cl_place is not null");
            return (Criteria) this;
        }

        public Criteria andClPlaceEqualTo(String value) {
            addCriterion("cl_place =", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceNotEqualTo(String value) {
            addCriterion("cl_place <>", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceGreaterThan(String value) {
            addCriterion("cl_place >", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("cl_place >=", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceLessThan(String value) {
            addCriterion("cl_place <", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceLessThanOrEqualTo(String value) {
            addCriterion("cl_place <=", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceLike(String value) {
            addCriterion("cl_place like", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceNotLike(String value) {
            addCriterion("cl_place not like", value, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceIn(List<String> values) {
            addCriterion("cl_place in", values, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceNotIn(List<String> values) {
            addCriterion("cl_place not in", values, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceBetween(String value1, String value2) {
            addCriterion("cl_place between", value1, value2, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClPlaceNotBetween(String value1, String value2) {
            addCriterion("cl_place not between", value1, value2, "clPlace");
            return (Criteria) this;
        }

        public Criteria andClContentIsNull() {
            addCriterion("cl_content is null");
            return (Criteria) this;
        }

        public Criteria andClContentIsNotNull() {
            addCriterion("cl_content is not null");
            return (Criteria) this;
        }

        public Criteria andClContentEqualTo(String value) {
            addCriterion("cl_content =", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentNotEqualTo(String value) {
            addCriterion("cl_content <>", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentGreaterThan(String value) {
            addCriterion("cl_content >", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentGreaterThanOrEqualTo(String value) {
            addCriterion("cl_content >=", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentLessThan(String value) {
            addCriterion("cl_content <", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentLessThanOrEqualTo(String value) {
            addCriterion("cl_content <=", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentLike(String value) {
            addCriterion("cl_content like", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentNotLike(String value) {
            addCriterion("cl_content not like", value, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentIn(List<String> values) {
            addCriterion("cl_content in", values, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentNotIn(List<String> values) {
            addCriterion("cl_content not in", values, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentBetween(String value1, String value2) {
            addCriterion("cl_content between", value1, value2, "clContent");
            return (Criteria) this;
        }

        public Criteria andClContentNotBetween(String value1, String value2) {
            addCriterion("cl_content not between", value1, value2, "clContent");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andClStateIsNull() {
            addCriterion("cl_state is null");
            return (Criteria) this;
        }

        public Criteria andClStateIsNotNull() {
            addCriterion("cl_state is not null");
            return (Criteria) this;
        }

        public Criteria andClStateEqualTo(Integer value) {
            addCriterion("cl_state =", value, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateNotEqualTo(Integer value) {
            addCriterion("cl_state <>", value, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateGreaterThan(Integer value) {
            addCriterion("cl_state >", value, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("cl_state >=", value, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateLessThan(Integer value) {
            addCriterion("cl_state <", value, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateLessThanOrEqualTo(Integer value) {
            addCriterion("cl_state <=", value, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateIn(List<Integer> values) {
            addCriterion("cl_state in", values, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateNotIn(List<Integer> values) {
            addCriterion("cl_state not in", values, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateBetween(Integer value1, Integer value2) {
            addCriterion("cl_state between", value1, value2, "clState");
            return (Criteria) this;
        }

        public Criteria andClStateNotBetween(Integer value1, Integer value2) {
            addCriterion("cl_state not between", value1, value2, "clState");
            return (Criteria) this;
        }

        public Criteria andCirculationIsNull() {
            addCriterion("circulation is null");
            return (Criteria) this;
        }

        public Criteria andCirculationIsNotNull() {
            addCriterion("circulation is not null");
            return (Criteria) this;
        }

        public Criteria andCirculationEqualTo(Integer value) {
            addCriterion("circulation =", value, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationNotEqualTo(Integer value) {
            addCriterion("circulation <>", value, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationGreaterThan(Integer value) {
            addCriterion("circulation >", value, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationGreaterThanOrEqualTo(Integer value) {
            addCriterion("circulation >=", value, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationLessThan(Integer value) {
            addCriterion("circulation <", value, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationLessThanOrEqualTo(Integer value) {
            addCriterion("circulation <=", value, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationIn(List<Integer> values) {
            addCriterion("circulation in", values, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationNotIn(List<Integer> values) {
            addCriterion("circulation not in", values, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationBetween(Integer value1, Integer value2) {
            addCriterion("circulation between", value1, value2, "circulation");
            return (Criteria) this;
        }

        public Criteria andCirculationNotBetween(Integer value1, Integer value2) {
            addCriterion("circulation not between", value1, value2, "circulation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clock
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clock
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}