package com.cn.exclusiveGirlfriend.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dress
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dress
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dress
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public DressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dress
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDidIsNull() {
            addCriterion("did is null");
            return (Criteria) this;
        }

        public Criteria andDidIsNotNull() {
            addCriterion("did is not null");
            return (Criteria) this;
        }

        public Criteria andDidEqualTo(Integer value) {
            addCriterion("did =", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotEqualTo(Integer value) {
            addCriterion("did <>", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThan(Integer value) {
            addCriterion("did >", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("did >=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThan(Integer value) {
            addCriterion("did <", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThanOrEqualTo(Integer value) {
            addCriterion("did <=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidIn(List<Integer> values) {
            addCriterion("did in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotIn(List<Integer> values) {
            addCriterion("did not in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidBetween(Integer value1, Integer value2) {
            addCriterion("did between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotBetween(Integer value1, Integer value2) {
            addCriterion("did not between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andClothesSizeIsNull() {
            addCriterion("clothes_size is null");
            return (Criteria) this;
        }

        public Criteria andClothesSizeIsNotNull() {
            addCriterion("clothes_size is not null");
            return (Criteria) this;
        }

        public Criteria andClothesSizeEqualTo(String value) {
            addCriterion("clothes_size =", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeNotEqualTo(String value) {
            addCriterion("clothes_size <>", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeGreaterThan(String value) {
            addCriterion("clothes_size >", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeGreaterThanOrEqualTo(String value) {
            addCriterion("clothes_size >=", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeLessThan(String value) {
            addCriterion("clothes_size <", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeLessThanOrEqualTo(String value) {
            addCriterion("clothes_size <=", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeLike(String value) {
            addCriterion("clothes_size like", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeNotLike(String value) {
            addCriterion("clothes_size not like", value, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeIn(List<String> values) {
            addCriterion("clothes_size in", values, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeNotIn(List<String> values) {
            addCriterion("clothes_size not in", values, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeBetween(String value1, String value2) {
            addCriterion("clothes_size between", value1, value2, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andClothesSizeNotBetween(String value1, String value2) {
            addCriterion("clothes_size not between", value1, value2, "clothesSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeIsNull() {
            addCriterion("trousers_size is null");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeIsNotNull() {
            addCriterion("trousers_size is not null");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeEqualTo(String value) {
            addCriterion("trousers_size =", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeNotEqualTo(String value) {
            addCriterion("trousers_size <>", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeGreaterThan(String value) {
            addCriterion("trousers_size >", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeGreaterThanOrEqualTo(String value) {
            addCriterion("trousers_size >=", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeLessThan(String value) {
            addCriterion("trousers_size <", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeLessThanOrEqualTo(String value) {
            addCriterion("trousers_size <=", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeLike(String value) {
            addCriterion("trousers_size like", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeNotLike(String value) {
            addCriterion("trousers_size not like", value, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeIn(List<String> values) {
            addCriterion("trousers_size in", values, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeNotIn(List<String> values) {
            addCriterion("trousers_size not in", values, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeBetween(String value1, String value2) {
            addCriterion("trousers_size between", value1, value2, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andTrousersSizeNotBetween(String value1, String value2) {
            addCriterion("trousers_size not between", value1, value2, "trousersSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeIsNull() {
            addCriterion("shoe_size is null");
            return (Criteria) this;
        }

        public Criteria andShoeSizeIsNotNull() {
            addCriterion("shoe_size is not null");
            return (Criteria) this;
        }

        public Criteria andShoeSizeEqualTo(String value) {
            addCriterion("shoe_size =", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeNotEqualTo(String value) {
            addCriterion("shoe_size <>", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeGreaterThan(String value) {
            addCriterion("shoe_size >", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeGreaterThanOrEqualTo(String value) {
            addCriterion("shoe_size >=", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeLessThan(String value) {
            addCriterion("shoe_size <", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeLessThanOrEqualTo(String value) {
            addCriterion("shoe_size <=", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeLike(String value) {
            addCriterion("shoe_size like", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeNotLike(String value) {
            addCriterion("shoe_size not like", value, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeIn(List<String> values) {
            addCriterion("shoe_size in", values, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeNotIn(List<String> values) {
            addCriterion("shoe_size not in", values, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeBetween(String value1, String value2) {
            addCriterion("shoe_size between", value1, value2, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andShoeSizeNotBetween(String value1, String value2) {
            addCriterion("shoe_size not between", value1, value2, "shoeSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeIsNull() {
            addCriterion("skirt_size is null");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeIsNotNull() {
            addCriterion("skirt_size is not null");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeEqualTo(String value) {
            addCriterion("skirt_size =", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeNotEqualTo(String value) {
            addCriterion("skirt_size <>", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeGreaterThan(String value) {
            addCriterion("skirt_size >", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeGreaterThanOrEqualTo(String value) {
            addCriterion("skirt_size >=", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeLessThan(String value) {
            addCriterion("skirt_size <", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeLessThanOrEqualTo(String value) {
            addCriterion("skirt_size <=", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeLike(String value) {
            addCriterion("skirt_size like", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeNotLike(String value) {
            addCriterion("skirt_size not like", value, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeIn(List<String> values) {
            addCriterion("skirt_size in", values, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeNotIn(List<String> values) {
            addCriterion("skirt_size not in", values, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeBetween(String value1, String value2) {
            addCriterion("skirt_size between", value1, value2, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andSkirtSizeNotBetween(String value1, String value2) {
            addCriterion("skirt_size not between", value1, value2, "skirtSize");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dress
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dress
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}