package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Dress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.clothes_size
     *
     * @mbg.generated
     */
    private String clothesSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.trousers_size
     *
     * @mbg.generated
     */
    private String trousersSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.shoe_size
     *
     * @mbg.generated
     */
    private String shoeSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.skirt_size
     *
     * @mbg.generated
     */
    private String skirtSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dress.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dress
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.did
     *
     * @return the value of dress.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.did
     *
     * @param did the value for dress.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.uid
     *
     * @return the value of dress.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.uid
     *
     * @param uid the value for dress.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.clothes_size
     *
     * @return the value of dress.clothes_size
     *
     * @mbg.generated
     */
    public String getClothesSize() {
        return clothesSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.clothes_size
     *
     * @param clothesSize the value for dress.clothes_size
     *
     * @mbg.generated
     */
    public void setClothesSize(String clothesSize) {
        this.clothesSize = clothesSize == null ? null : clothesSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.trousers_size
     *
     * @return the value of dress.trousers_size
     *
     * @mbg.generated
     */
    public String getTrousersSize() {
        return trousersSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.trousers_size
     *
     * @param trousersSize the value for dress.trousers_size
     *
     * @mbg.generated
     */
    public void setTrousersSize(String trousersSize) {
        this.trousersSize = trousersSize == null ? null : trousersSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.shoe_size
     *
     * @return the value of dress.shoe_size
     *
     * @mbg.generated
     */
    public String getShoeSize() {
        return shoeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.shoe_size
     *
     * @param shoeSize the value for dress.shoe_size
     *
     * @mbg.generated
     */
    public void setShoeSize(String shoeSize) {
        this.shoeSize = shoeSize == null ? null : shoeSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.skirt_size
     *
     * @return the value of dress.skirt_size
     *
     * @mbg.generated
     */
    public String getSkirtSize() {
        return skirtSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.skirt_size
     *
     * @param skirtSize the value for dress.skirt_size
     *
     * @mbg.generated
     */
    public void setSkirtSize(String skirtSize) {
        this.skirtSize = skirtSize == null ? null : skirtSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dress.createtime
     *
     * @return the value of dress.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dress.createtime
     *
     * @param createtime the value for dress.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}