package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Envelope implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.e_id
     *
     * @mbg.generated
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.e_title
     *
     * @mbg.generated
     */
    private String eTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.e_type
     *
     * @mbg.generated
     */
    private String eType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.e_content
     *
     * @mbg.generated
     */
    private String eContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.e_fsstate
     *
     * @mbg.generated
     */
    private Integer eFsstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.e_jsstate
     *
     * @mbg.generated
     */
    private Integer eJsstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.fs_id
     *
     * @mbg.generated
     */
    private Integer fsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column envelope.js_id
     *
     * @mbg.generated
     */
    private Integer jsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table envelope
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.e_id
     *
     * @return the value of envelope.e_id
     *
     * @mbg.generated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.e_id
     *
     * @param eId the value for envelope.e_id
     *
     * @mbg.generated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.e_title
     *
     * @return the value of envelope.e_title
     *
     * @mbg.generated
     */
    public String geteTitle() {
        return eTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.e_title
     *
     * @param eTitle the value for envelope.e_title
     *
     * @mbg.generated
     */
    public void seteTitle(String eTitle) {
        this.eTitle = eTitle == null ? null : eTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.e_type
     *
     * @return the value of envelope.e_type
     *
     * @mbg.generated
     */
    public String geteType() {
        return eType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.e_type
     *
     * @param eType the value for envelope.e_type
     *
     * @mbg.generated
     */
    public void seteType(String eType) {
        this.eType = eType == null ? null : eType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.e_content
     *
     * @return the value of envelope.e_content
     *
     * @mbg.generated
     */
    public String geteContent() {
        return eContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.e_content
     *
     * @param eContent the value for envelope.e_content
     *
     * @mbg.generated
     */
    public void seteContent(String eContent) {
        this.eContent = eContent == null ? null : eContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.createtime
     *
     * @return the value of envelope.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.createtime
     *
     * @param createtime the value for envelope.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.e_fsstate
     *
     * @return the value of envelope.e_fsstate
     *
     * @mbg.generated
     */
    public Integer geteFsstate() {
        return eFsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.e_fsstate
     *
     * @param eFsstate the value for envelope.e_fsstate
     *
     * @mbg.generated
     */
    public void seteFsstate(Integer eFsstate) {
        this.eFsstate = eFsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.e_jsstate
     *
     * @return the value of envelope.e_jsstate
     *
     * @mbg.generated
     */
    public Integer geteJsstate() {
        return eJsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.e_jsstate
     *
     * @param eJsstate the value for envelope.e_jsstate
     *
     * @mbg.generated
     */
    public void seteJsstate(Integer eJsstate) {
        this.eJsstate = eJsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.fs_id
     *
     * @return the value of envelope.fs_id
     *
     * @mbg.generated
     */
    public Integer getFsId() {
        return fsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.fs_id
     *
     * @param fsId the value for envelope.fs_id
     *
     * @mbg.generated
     */
    public void setFsId(Integer fsId) {
        this.fsId = fsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column envelope.js_id
     *
     * @return the value of envelope.js_id
     *
     * @mbg.generated
     */
    public Integer getJsId() {
        return jsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column envelope.js_id
     *
     * @param jsId the value for envelope.js_id
     *
     * @mbg.generated
     */
    public void setJsId(Integer jsId) {
        this.jsId = jsId;
    }
}