package com.cn.exclusiveGirlfriend.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnvelopeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table envelope
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table envelope
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table envelope
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public EnvelopeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table envelope
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEIdIsNull() {
            addCriterion("e_id is null");
            return (Criteria) this;
        }

        public Criteria andEIdIsNotNull() {
            addCriterion("e_id is not null");
            return (Criteria) this;
        }

        public Criteria andEIdEqualTo(Integer value) {
            addCriterion("e_id =", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotEqualTo(Integer value) {
            addCriterion("e_id <>", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdGreaterThan(Integer value) {
            addCriterion("e_id >", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_id >=", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdLessThan(Integer value) {
            addCriterion("e_id <", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdLessThanOrEqualTo(Integer value) {
            addCriterion("e_id <=", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdIn(List<Integer> values) {
            addCriterion("e_id in", values, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotIn(List<Integer> values) {
            addCriterion("e_id not in", values, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdBetween(Integer value1, Integer value2) {
            addCriterion("e_id between", value1, value2, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotBetween(Integer value1, Integer value2) {
            addCriterion("e_id not between", value1, value2, "eId");
            return (Criteria) this;
        }

        public Criteria andETitleIsNull() {
            addCriterion("e_title is null");
            return (Criteria) this;
        }

        public Criteria andETitleIsNotNull() {
            addCriterion("e_title is not null");
            return (Criteria) this;
        }

        public Criteria andETitleEqualTo(String value) {
            addCriterion("e_title =", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleNotEqualTo(String value) {
            addCriterion("e_title <>", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleGreaterThan(String value) {
            addCriterion("e_title >", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleGreaterThanOrEqualTo(String value) {
            addCriterion("e_title >=", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleLessThan(String value) {
            addCriterion("e_title <", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleLessThanOrEqualTo(String value) {
            addCriterion("e_title <=", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleLike(String value) {
            addCriterion("e_title like", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleNotLike(String value) {
            addCriterion("e_title not like", value, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleIn(List<String> values) {
            addCriterion("e_title in", values, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleNotIn(List<String> values) {
            addCriterion("e_title not in", values, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleBetween(String value1, String value2) {
            addCriterion("e_title between", value1, value2, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETitleNotBetween(String value1, String value2) {
            addCriterion("e_title not between", value1, value2, "eTitle");
            return (Criteria) this;
        }

        public Criteria andETypeIsNull() {
            addCriterion("e_type is null");
            return (Criteria) this;
        }

        public Criteria andETypeIsNotNull() {
            addCriterion("e_type is not null");
            return (Criteria) this;
        }

        public Criteria andETypeEqualTo(String value) {
            addCriterion("e_type =", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotEqualTo(String value) {
            addCriterion("e_type <>", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeGreaterThan(String value) {
            addCriterion("e_type >", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeGreaterThanOrEqualTo(String value) {
            addCriterion("e_type >=", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeLessThan(String value) {
            addCriterion("e_type <", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeLessThanOrEqualTo(String value) {
            addCriterion("e_type <=", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeLike(String value) {
            addCriterion("e_type like", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotLike(String value) {
            addCriterion("e_type not like", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeIn(List<String> values) {
            addCriterion("e_type in", values, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotIn(List<String> values) {
            addCriterion("e_type not in", values, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeBetween(String value1, String value2) {
            addCriterion("e_type between", value1, value2, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotBetween(String value1, String value2) {
            addCriterion("e_type not between", value1, value2, "eType");
            return (Criteria) this;
        }

        public Criteria andEContentIsNull() {
            addCriterion("e_content is null");
            return (Criteria) this;
        }

        public Criteria andEContentIsNotNull() {
            addCriterion("e_content is not null");
            return (Criteria) this;
        }

        public Criteria andEContentEqualTo(String value) {
            addCriterion("e_content =", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotEqualTo(String value) {
            addCriterion("e_content <>", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentGreaterThan(String value) {
            addCriterion("e_content >", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentGreaterThanOrEqualTo(String value) {
            addCriterion("e_content >=", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentLessThan(String value) {
            addCriterion("e_content <", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentLessThanOrEqualTo(String value) {
            addCriterion("e_content <=", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentLike(String value) {
            addCriterion("e_content like", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotLike(String value) {
            addCriterion("e_content not like", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentIn(List<String> values) {
            addCriterion("e_content in", values, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotIn(List<String> values) {
            addCriterion("e_content not in", values, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentBetween(String value1, String value2) {
            addCriterion("e_content between", value1, value2, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotBetween(String value1, String value2) {
            addCriterion("e_content not between", value1, value2, "eContent");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andEFsstateIsNull() {
            addCriterion("e_fsstate is null");
            return (Criteria) this;
        }

        public Criteria andEFsstateIsNotNull() {
            addCriterion("e_fsstate is not null");
            return (Criteria) this;
        }

        public Criteria andEFsstateEqualTo(Integer value) {
            addCriterion("e_fsstate =", value, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateNotEqualTo(Integer value) {
            addCriterion("e_fsstate <>", value, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateGreaterThan(Integer value) {
            addCriterion("e_fsstate >", value, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_fsstate >=", value, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateLessThan(Integer value) {
            addCriterion("e_fsstate <", value, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateLessThanOrEqualTo(Integer value) {
            addCriterion("e_fsstate <=", value, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateIn(List<Integer> values) {
            addCriterion("e_fsstate in", values, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateNotIn(List<Integer> values) {
            addCriterion("e_fsstate not in", values, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateBetween(Integer value1, Integer value2) {
            addCriterion("e_fsstate between", value1, value2, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEFsstateNotBetween(Integer value1, Integer value2) {
            addCriterion("e_fsstate not between", value1, value2, "eFsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateIsNull() {
            addCriterion("e_jsstate is null");
            return (Criteria) this;
        }

        public Criteria andEJsstateIsNotNull() {
            addCriterion("e_jsstate is not null");
            return (Criteria) this;
        }

        public Criteria andEJsstateEqualTo(Integer value) {
            addCriterion("e_jsstate =", value, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateNotEqualTo(Integer value) {
            addCriterion("e_jsstate <>", value, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateGreaterThan(Integer value) {
            addCriterion("e_jsstate >", value, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_jsstate >=", value, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateLessThan(Integer value) {
            addCriterion("e_jsstate <", value, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateLessThanOrEqualTo(Integer value) {
            addCriterion("e_jsstate <=", value, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateIn(List<Integer> values) {
            addCriterion("e_jsstate in", values, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateNotIn(List<Integer> values) {
            addCriterion("e_jsstate not in", values, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateBetween(Integer value1, Integer value2) {
            addCriterion("e_jsstate between", value1, value2, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andEJsstateNotBetween(Integer value1, Integer value2) {
            addCriterion("e_jsstate not between", value1, value2, "eJsstate");
            return (Criteria) this;
        }

        public Criteria andFsIdIsNull() {
            addCriterion("fs_id is null");
            return (Criteria) this;
        }

        public Criteria andFsIdIsNotNull() {
            addCriterion("fs_id is not null");
            return (Criteria) this;
        }

        public Criteria andFsIdEqualTo(Integer value) {
            addCriterion("fs_id =", value, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdNotEqualTo(Integer value) {
            addCriterion("fs_id <>", value, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdGreaterThan(Integer value) {
            addCriterion("fs_id >", value, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fs_id >=", value, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdLessThan(Integer value) {
            addCriterion("fs_id <", value, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdLessThanOrEqualTo(Integer value) {
            addCriterion("fs_id <=", value, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdIn(List<Integer> values) {
            addCriterion("fs_id in", values, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdNotIn(List<Integer> values) {
            addCriterion("fs_id not in", values, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdBetween(Integer value1, Integer value2) {
            addCriterion("fs_id between", value1, value2, "fsId");
            return (Criteria) this;
        }

        public Criteria andFsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fs_id not between", value1, value2, "fsId");
            return (Criteria) this;
        }

        public Criteria andJsIdIsNull() {
            addCriterion("js_id is null");
            return (Criteria) this;
        }

        public Criteria andJsIdIsNotNull() {
            addCriterion("js_id is not null");
            return (Criteria) this;
        }

        public Criteria andJsIdEqualTo(Integer value) {
            addCriterion("js_id =", value, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdNotEqualTo(Integer value) {
            addCriterion("js_id <>", value, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdGreaterThan(Integer value) {
            addCriterion("js_id >", value, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("js_id >=", value, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdLessThan(Integer value) {
            addCriterion("js_id <", value, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdLessThanOrEqualTo(Integer value) {
            addCriterion("js_id <=", value, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdIn(List<Integer> values) {
            addCriterion("js_id in", values, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdNotIn(List<Integer> values) {
            addCriterion("js_id not in", values, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdBetween(Integer value1, Integer value2) {
            addCriterion("js_id between", value1, value2, "jsId");
            return (Criteria) this;
        }

        public Criteria andJsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("js_id not between", value1, value2, "jsId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table envelope
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table envelope
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}