package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Feedback implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.f_id
     *
     * @mbg.generated
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.f_content
     *
     * @mbg.generated
     */
    private String fContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.f_state
     *
     * @mbg.generated
     */
    private Integer fState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.f_demand
     *
     * @mbg.generated
     */
    private String fDemand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.f_title
     *
     * @mbg.generated
     */
    private String fTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.f_id
     *
     * @return the value of feedback.f_id
     *
     * @mbg.generated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.f_id
     *
     * @param fId the value for feedback.f_id
     *
     * @mbg.generated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.f_content
     *
     * @return the value of feedback.f_content
     *
     * @mbg.generated
     */
    public String getfContent() {
        return fContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.f_content
     *
     * @param fContent the value for feedback.f_content
     *
     * @mbg.generated
     */
    public void setfContent(String fContent) {
        this.fContent = fContent == null ? null : fContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.f_state
     *
     * @return the value of feedback.f_state
     *
     * @mbg.generated
     */
    public Integer getfState() {
        return fState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.f_state
     *
     * @param fState the value for feedback.f_state
     *
     * @mbg.generated
     */
    public void setfState(Integer fState) {
        this.fState = fState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.createtime
     *
     * @return the value of feedback.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.createtime
     *
     * @param createtime the value for feedback.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.f_demand
     *
     * @return the value of feedback.f_demand
     *
     * @mbg.generated
     */
    public String getfDemand() {
        return fDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.f_demand
     *
     * @param fDemand the value for feedback.f_demand
     *
     * @mbg.generated
     */
    public void setfDemand(String fDemand) {
        this.fDemand = fDemand == null ? null : fDemand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.f_title
     *
     * @return the value of feedback.f_title
     *
     * @mbg.generated
     */
    public String getfTitle() {
        return fTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.f_title
     *
     * @param fTitle the value for feedback.f_title
     *
     * @mbg.generated
     */
    public void setfTitle(String fTitle) {
        this.fTitle = fTitle == null ? null : fTitle.trim();
    }
}