package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Girllike implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_id
     *
     * @mbg.generated
     */
    private Integer glId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_name
     *
     * @mbg.generated
     */
    private String glName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_color
     *
     * @mbg.generated
     */
    private String glColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_style
     *
     * @mbg.generated
     */
    private String glStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_type
     *
     * @mbg.generated
     */
    private String glType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_size
     *
     * @mbg.generated
     */
    private Integer glSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_level
     *
     * @mbg.generated
     */
    private Integer glLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girllike.gl_state
     *
     * @mbg.generated
     */
    private Integer glState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table girllike
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_id
     *
     * @return the value of girllike.gl_id
     *
     * @mbg.generated
     */
    public Integer getGlId() {
        return glId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_id
     *
     * @param glId the value for girllike.gl_id
     *
     * @mbg.generated
     */
    public void setGlId(Integer glId) {
        this.glId = glId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_name
     *
     * @return the value of girllike.gl_name
     *
     * @mbg.generated
     */
    public String getGlName() {
        return glName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_name
     *
     * @param glName the value for girllike.gl_name
     *
     * @mbg.generated
     */
    public void setGlName(String glName) {
        this.glName = glName == null ? null : glName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_color
     *
     * @return the value of girllike.gl_color
     *
     * @mbg.generated
     */
    public String getGlColor() {
        return glColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_color
     *
     * @param glColor the value for girllike.gl_color
     *
     * @mbg.generated
     */
    public void setGlColor(String glColor) {
        this.glColor = glColor == null ? null : glColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_style
     *
     * @return the value of girllike.gl_style
     *
     * @mbg.generated
     */
    public String getGlStyle() {
        return glStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_style
     *
     * @param glStyle the value for girllike.gl_style
     *
     * @mbg.generated
     */
    public void setGlStyle(String glStyle) {
        this.glStyle = glStyle == null ? null : glStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_type
     *
     * @return the value of girllike.gl_type
     *
     * @mbg.generated
     */
    public String getGlType() {
        return glType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_type
     *
     * @param glType the value for girllike.gl_type
     *
     * @mbg.generated
     */
    public void setGlType(String glType) {
        this.glType = glType == null ? null : glType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_size
     *
     * @return the value of girllike.gl_size
     *
     * @mbg.generated
     */
    public Integer getGlSize() {
        return glSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_size
     *
     * @param glSize the value for girllike.gl_size
     *
     * @mbg.generated
     */
    public void setGlSize(Integer glSize) {
        this.glSize = glSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.createtime
     *
     * @return the value of girllike.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.createtime
     *
     * @param createtime the value for girllike.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_level
     *
     * @return the value of girllike.gl_level
     *
     * @mbg.generated
     */
    public Integer getGlLevel() {
        return glLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_level
     *
     * @param glLevel the value for girllike.gl_level
     *
     * @mbg.generated
     */
    public void setGlLevel(Integer glLevel) {
        this.glLevel = glLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girllike.gl_state
     *
     * @return the value of girllike.gl_state
     *
     * @mbg.generated
     */
    public Integer getGlState() {
        return glState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girllike.gl_state
     *
     * @param glState the value for girllike.gl_state
     *
     * @mbg.generated
     */
    public void setGlState(Integer glState) {
        this.glState = glState;
    }
}