package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Legal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.l_id
     *
     * @mbg.generated
     */
    private Integer lId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.l_time
     *
     * @mbg.generated
     */
    private Date lTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.creattime
     *
     * @mbg.generated
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.starttime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.delay
     *
     * @mbg.generated
     */
    private Integer delay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.flow
     *
     * @mbg.generated
     */
    private Integer flow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal.pain
     *
     * @mbg.generated
     */
    private String pain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table legal
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.l_id
     *
     * @return the value of legal.l_id
     *
     * @mbg.generated
     */
    public Integer getlId() {
        return lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.l_id
     *
     * @param lId the value for legal.l_id
     *
     * @mbg.generated
     */
    public void setlId(Integer lId) {
        this.lId = lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.l_time
     *
     * @return the value of legal.l_time
     *
     * @mbg.generated
     */
    public Date getlTime() {
        return lTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.l_time
     *
     * @param lTime the value for legal.l_time
     *
     * @mbg.generated
     */
    public void setlTime(Date lTime) {
        this.lTime = lTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.creattime
     *
     * @return the value of legal.creattime
     *
     * @mbg.generated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.creattime
     *
     * @param creattime the value for legal.creattime
     *
     * @mbg.generated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.state
     *
     * @return the value of legal.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.state
     *
     * @param state the value for legal.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.starttime
     *
     * @return the value of legal.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.starttime
     *
     * @param starttime the value for legal.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.endtime
     *
     * @return the value of legal.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.endtime
     *
     * @param endtime the value for legal.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.delay
     *
     * @return the value of legal.delay
     *
     * @mbg.generated
     */
    public Integer getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.delay
     *
     * @param delay the value for legal.delay
     *
     * @mbg.generated
     */
    public void setDelay(Integer delay) {
        this.delay = delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.flow
     *
     * @return the value of legal.flow
     *
     * @mbg.generated
     */
    public Integer getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.flow
     *
     * @param flow the value for legal.flow
     *
     * @mbg.generated
     */
    public void setFlow(Integer flow) {
        this.flow = flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal.pain
     *
     * @return the value of legal.pain
     *
     * @mbg.generated
     */
    public String getPain() {
        return pain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal.pain
     *
     * @param pain the value for legal.pain
     *
     * @mbg.generated
     */
    public void setPain(String pain) {
        this.pain = pain == null ? null : pain.trim();
    }
}