package com.cn.exclusiveGirlfriend.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OperationrecordsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public OperationrecordsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOidIsNull() {
            addCriterion("oid is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oid is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(Integer value) {
            addCriterion("oid =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(Integer value) {
            addCriterion("oid <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(Integer value) {
            addCriterion("oid >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("oid >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(Integer value) {
            addCriterion("oid <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(Integer value) {
            addCriterion("oid <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<Integer> values) {
            addCriterion("oid in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<Integer> values) {
            addCriterion("oid not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(Integer value1, Integer value2) {
            addCriterion("oid between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(Integer value1, Integer value2) {
            addCriterion("oid not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOperationipIsNull() {
            addCriterion("operationIp is null");
            return (Criteria) this;
        }

        public Criteria andOperationipIsNotNull() {
            addCriterion("operationIp is not null");
            return (Criteria) this;
        }

        public Criteria andOperationipEqualTo(String value) {
            addCriterion("operationIp =", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipNotEqualTo(String value) {
            addCriterion("operationIp <>", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipGreaterThan(String value) {
            addCriterion("operationIp >", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipGreaterThanOrEqualTo(String value) {
            addCriterion("operationIp >=", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipLessThan(String value) {
            addCriterion("operationIp <", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipLessThanOrEqualTo(String value) {
            addCriterion("operationIp <=", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipLike(String value) {
            addCriterion("operationIp like", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipNotLike(String value) {
            addCriterion("operationIp not like", value, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipIn(List<String> values) {
            addCriterion("operationIp in", values, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipNotIn(List<String> values) {
            addCriterion("operationIp not in", values, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipBetween(String value1, String value2) {
            addCriterion("operationIp between", value1, value2, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationipNotBetween(String value1, String value2) {
            addCriterion("operationIp not between", value1, value2, "operationip");
            return (Criteria) this;
        }

        public Criteria andOperationnameIsNull() {
            addCriterion("operationName is null");
            return (Criteria) this;
        }

        public Criteria andOperationnameIsNotNull() {
            addCriterion("operationName is not null");
            return (Criteria) this;
        }

        public Criteria andOperationnameEqualTo(String value) {
            addCriterion("operationName =", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameNotEqualTo(String value) {
            addCriterion("operationName <>", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameGreaterThan(String value) {
            addCriterion("operationName >", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameGreaterThanOrEqualTo(String value) {
            addCriterion("operationName >=", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameLessThan(String value) {
            addCriterion("operationName <", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameLessThanOrEqualTo(String value) {
            addCriterion("operationName <=", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameLike(String value) {
            addCriterion("operationName like", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameNotLike(String value) {
            addCriterion("operationName not like", value, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameIn(List<String> values) {
            addCriterion("operationName in", values, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameNotIn(List<String> values) {
            addCriterion("operationName not in", values, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameBetween(String value1, String value2) {
            addCriterion("operationName between", value1, value2, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationnameNotBetween(String value1, String value2) {
            addCriterion("operationName not between", value1, value2, "operationname");
            return (Criteria) this;
        }

        public Criteria andOperationserviceIsNull() {
            addCriterion("operationService is null");
            return (Criteria) this;
        }

        public Criteria andOperationserviceIsNotNull() {
            addCriterion("operationService is not null");
            return (Criteria) this;
        }

        public Criteria andOperationserviceEqualTo(String value) {
            addCriterion("operationService =", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceNotEqualTo(String value) {
            addCriterion("operationService <>", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceGreaterThan(String value) {
            addCriterion("operationService >", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceGreaterThanOrEqualTo(String value) {
            addCriterion("operationService >=", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceLessThan(String value) {
            addCriterion("operationService <", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceLessThanOrEqualTo(String value) {
            addCriterion("operationService <=", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceLike(String value) {
            addCriterion("operationService like", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceNotLike(String value) {
            addCriterion("operationService not like", value, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceIn(List<String> values) {
            addCriterion("operationService in", values, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceNotIn(List<String> values) {
            addCriterion("operationService not in", values, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceBetween(String value1, String value2) {
            addCriterion("operationService between", value1, value2, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationserviceNotBetween(String value1, String value2) {
            addCriterion("operationService not between", value1, value2, "operationservice");
            return (Criteria) this;
        }

        public Criteria andOperationremarkIsNull() {
            addCriterion("operationRemark is null");
            return (Criteria) this;
        }

        public Criteria andOperationremarkIsNotNull() {
            addCriterion("operationRemark is not null");
            return (Criteria) this;
        }

        public Criteria andOperationremarkEqualTo(String value) {
            addCriterion("operationRemark =", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkNotEqualTo(String value) {
            addCriterion("operationRemark <>", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkGreaterThan(String value) {
            addCriterion("operationRemark >", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkGreaterThanOrEqualTo(String value) {
            addCriterion("operationRemark >=", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkLessThan(String value) {
            addCriterion("operationRemark <", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkLessThanOrEqualTo(String value) {
            addCriterion("operationRemark <=", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkLike(String value) {
            addCriterion("operationRemark like", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkNotLike(String value) {
            addCriterion("operationRemark not like", value, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkIn(List<String> values) {
            addCriterion("operationRemark in", values, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkNotIn(List<String> values) {
            addCriterion("operationRemark not in", values, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkBetween(String value1, String value2) {
            addCriterion("operationRemark between", value1, value2, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationremarkNotBetween(String value1, String value2) {
            addCriterion("operationRemark not between", value1, value2, "operationremark");
            return (Criteria) this;
        }

        public Criteria andOperationdataIsNull() {
            addCriterion("operationData is null");
            return (Criteria) this;
        }

        public Criteria andOperationdataIsNotNull() {
            addCriterion("operationData is not null");
            return (Criteria) this;
        }

        public Criteria andOperationdataEqualTo(String value) {
            addCriterion("operationData =", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataNotEqualTo(String value) {
            addCriterion("operationData <>", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataGreaterThan(String value) {
            addCriterion("operationData >", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataGreaterThanOrEqualTo(String value) {
            addCriterion("operationData >=", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataLessThan(String value) {
            addCriterion("operationData <", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataLessThanOrEqualTo(String value) {
            addCriterion("operationData <=", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataLike(String value) {
            addCriterion("operationData like", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataNotLike(String value) {
            addCriterion("operationData not like", value, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataIn(List<String> values) {
            addCriterion("operationData in", values, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataNotIn(List<String> values) {
            addCriterion("operationData not in", values, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataBetween(String value1, String value2) {
            addCriterion("operationData between", value1, value2, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationdataNotBetween(String value1, String value2) {
            addCriterion("operationData not between", value1, value2, "operationdata");
            return (Criteria) this;
        }

        public Criteria andOperationresultIsNull() {
            addCriterion("operationResult is null");
            return (Criteria) this;
        }

        public Criteria andOperationresultIsNotNull() {
            addCriterion("operationResult is not null");
            return (Criteria) this;
        }

        public Criteria andOperationresultEqualTo(String value) {
            addCriterion("operationResult =", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultNotEqualTo(String value) {
            addCriterion("operationResult <>", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultGreaterThan(String value) {
            addCriterion("operationResult >", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultGreaterThanOrEqualTo(String value) {
            addCriterion("operationResult >=", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultLessThan(String value) {
            addCriterion("operationResult <", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultLessThanOrEqualTo(String value) {
            addCriterion("operationResult <=", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultLike(String value) {
            addCriterion("operationResult like", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultNotLike(String value) {
            addCriterion("operationResult not like", value, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultIn(List<String> values) {
            addCriterion("operationResult in", values, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultNotIn(List<String> values) {
            addCriterion("operationResult not in", values, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultBetween(String value1, String value2) {
            addCriterion("operationResult between", value1, value2, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationresultNotBetween(String value1, String value2) {
            addCriterion("operationResult not between", value1, value2, "operationresult");
            return (Criteria) this;
        }

        public Criteria andOperationtypeIsNull() {
            addCriterion("operationType is null");
            return (Criteria) this;
        }

        public Criteria andOperationtypeIsNotNull() {
            addCriterion("operationType is not null");
            return (Criteria) this;
        }

        public Criteria andOperationtypeEqualTo(String value) {
            addCriterion("operationType =", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotEqualTo(String value) {
            addCriterion("operationType <>", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeGreaterThan(String value) {
            addCriterion("operationType >", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeGreaterThanOrEqualTo(String value) {
            addCriterion("operationType >=", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeLessThan(String value) {
            addCriterion("operationType <", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeLessThanOrEqualTo(String value) {
            addCriterion("operationType <=", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeLike(String value) {
            addCriterion("operationType like", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotLike(String value) {
            addCriterion("operationType not like", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeIn(List<String> values) {
            addCriterion("operationType in", values, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotIn(List<String> values) {
            addCriterion("operationType not in", values, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeBetween(String value1, String value2) {
            addCriterion("operationType between", value1, value2, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotBetween(String value1, String value2) {
            addCriterion("operationType not between", value1, value2, "operationtype");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operationrecords
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}