package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Operationrecords implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationIp
     *
     * @mbg.generated
     */
    private String operationip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationName
     *
     * @mbg.generated
     */
    private String operationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationService
     *
     * @mbg.generated
     */
    private String operationservice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationRemark
     *
     * @mbg.generated
     */
    private String operationremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationData
     *
     * @mbg.generated
     */
    private String operationdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationResult
     *
     * @mbg.generated
     */
    private String operationresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.operationType
     *
     * @mbg.generated
     */
    private String operationtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecords.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.oid
     *
     * @return the value of operationrecords.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.oid
     *
     * @param oid the value for operationrecords.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationIp
     *
     * @return the value of operationrecords.operationIp
     *
     * @mbg.generated
     */
    public String getOperationip() {
        return operationip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationIp
     *
     * @param operationip the value for operationrecords.operationIp
     *
     * @mbg.generated
     */
    public void setOperationip(String operationip) {
        this.operationip = operationip == null ? null : operationip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationName
     *
     * @return the value of operationrecords.operationName
     *
     * @mbg.generated
     */
    public String getOperationname() {
        return operationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationName
     *
     * @param operationname the value for operationrecords.operationName
     *
     * @mbg.generated
     */
    public void setOperationname(String operationname) {
        this.operationname = operationname == null ? null : operationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationService
     *
     * @return the value of operationrecords.operationService
     *
     * @mbg.generated
     */
    public String getOperationservice() {
        return operationservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationService
     *
     * @param operationservice the value for operationrecords.operationService
     *
     * @mbg.generated
     */
    public void setOperationservice(String operationservice) {
        this.operationservice = operationservice == null ? null : operationservice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationRemark
     *
     * @return the value of operationrecords.operationRemark
     *
     * @mbg.generated
     */
    public String getOperationremark() {
        return operationremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationRemark
     *
     * @param operationremark the value for operationrecords.operationRemark
     *
     * @mbg.generated
     */
    public void setOperationremark(String operationremark) {
        this.operationremark = operationremark == null ? null : operationremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationData
     *
     * @return the value of operationrecords.operationData
     *
     * @mbg.generated
     */
    public String getOperationdata() {
        return operationdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationData
     *
     * @param operationdata the value for operationrecords.operationData
     *
     * @mbg.generated
     */
    public void setOperationdata(String operationdata) {
        this.operationdata = operationdata == null ? null : operationdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationResult
     *
     * @return the value of operationrecords.operationResult
     *
     * @mbg.generated
     */
    public String getOperationresult() {
        return operationresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationResult
     *
     * @param operationresult the value for operationrecords.operationResult
     *
     * @mbg.generated
     */
    public void setOperationresult(String operationresult) {
        this.operationresult = operationresult == null ? null : operationresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.operationType
     *
     * @return the value of operationrecords.operationType
     *
     * @mbg.generated
     */
    public String getOperationtype() {
        return operationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.operationType
     *
     * @param operationtype the value for operationrecords.operationType
     *
     * @mbg.generated
     */
    public void setOperationtype(String operationtype) {
        this.operationtype = operationtype == null ? null : operationtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecords.createtime
     *
     * @return the value of operationrecords.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecords.createtime
     *
     * @param createtime the value for operationrecords.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}