package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleid
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolename
     *
     * @mbg.generated
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolecreattime
     *
     * @mbg.generated
     */
    private Date rolecreattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleid
     *
     * @return the value of role.roleid
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleid
     *
     * @param roleid the value for role.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolename
     *
     * @return the value of role.rolename
     *
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolename
     *
     * @param rolename the value for role.rolename
     *
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolecreattime
     *
     * @return the value of role.rolecreattime
     *
     * @mbg.generated
     */
    public Date getRolecreattime() {
        return rolecreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolecreattime
     *
     * @param rolecreattime the value for role.rolecreattime
     *
     * @mbg.generated
     */
    public void setRolecreattime(Date rolecreattime) {
        this.rolecreattime = rolecreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.content
     *
     * @return the value of role.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.content
     *
     * @param content the value for role.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}