package com.cn.exclusiveGirlfriend.pojo;

import java.io.Serializable;
import java.util.Date;

public class Transporttype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transporttype.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transporttype.t_name
     *
     * @mbg.generated
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transporttype.t_content
     *
     * @mbg.generated
     */
    private String tContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transporttype.t_creattime
     *
     * @mbg.generated
     */
    private Date tCreattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transporttype.t_state
     *
     * @mbg.generated
     */
    private Integer tState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transporttype
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transporttype.t_id
     *
     * @return the value of transporttype.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transporttype.t_id
     *
     * @param tId the value for transporttype.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transporttype.t_name
     *
     * @return the value of transporttype.t_name
     *
     * @mbg.generated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transporttype.t_name
     *
     * @param tName the value for transporttype.t_name
     *
     * @mbg.generated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transporttype.t_content
     *
     * @return the value of transporttype.t_content
     *
     * @mbg.generated
     */
    public String gettContent() {
        return tContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transporttype.t_content
     *
     * @param tContent the value for transporttype.t_content
     *
     * @mbg.generated
     */
    public void settContent(String tContent) {
        this.tContent = tContent == null ? null : tContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transporttype.t_creattime
     *
     * @return the value of transporttype.t_creattime
     *
     * @mbg.generated
     */
    public Date gettCreattime() {
        return tCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transporttype.t_creattime
     *
     * @param tCreattime the value for transporttype.t_creattime
     *
     * @mbg.generated
     */
    public void settCreattime(Date tCreattime) {
        this.tCreattime = tCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transporttype.t_state
     *
     * @return the value of transporttype.t_state
     *
     * @mbg.generated
     */
    public Integer gettState() {
        return tState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transporttype.t_state
     *
     * @param tState the value for transporttype.t_state
     *
     * @mbg.generated
     */
    public void settState(Integer tState) {
        this.tState = tState;
    }
}