package com.cn.exclusiveGirlfriend.mapper;

import com.cn.exclusiveGirlfriend.pojo.Alongrecord;
import com.cn.exclusiveGirlfriend.pojo.AlongrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlongrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    long countByExample(AlongrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int deleteByExample(AlongrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int insert(Alongrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int insertSelective(Alongrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    List<Alongrecord> selectByExample(AlongrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    Alongrecord selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Alongrecord record, @Param("example") AlongrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Alongrecord record, @Param("example") AlongrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Alongrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alongrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Alongrecord record);
}