package com.cn.exclusiveGirlfriend.mapper;

import com.cn.exclusiveGirlfriend.pojo.Dress;
import com.cn.exclusiveGirlfriend.pojo.DressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    long countByExample(DressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int deleteByExample(DressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int insert(Dress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int insertSelective(Dress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    List<Dress> selectByExample(DressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    Dress selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dress record, @Param("example") DressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dress record, @Param("example") DressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dress
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dress record);
}