package com.cn.exclusiveGirlfriend.mapper;

import com.cn.exclusiveGirlfriend.pojo.Envelope;
import com.cn.exclusiveGirlfriend.pojo.EnvelopeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnvelopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    long countByExample(EnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int deleteByExample(EnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int insert(Envelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int insertSelective(Envelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    List<Envelope> selectByExample(EnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    Envelope selectByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Envelope record, @Param("example") EnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Envelope record, @Param("example") EnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Envelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table envelope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Envelope record);
}