package com.cn.exclusiveGirlfriend.mapper;

import com.cn.exclusiveGirlfriend.pojo.Legal;
import com.cn.exclusiveGirlfriend.pojo.LegalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LegalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    long countByExample(LegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int deleteByExample(LegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int insert(Legal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int insertSelective(Legal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    List<Legal> selectByExample(LegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    Legal selectByPrimaryKey(Integer lId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Legal record, @Param("example") LegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Legal record, @Param("example") LegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Legal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Legal record);
}