package com.cn.exclusiveGirlfriend.mapper;

import com.cn.exclusiveGirlfriend.pojo.Operationrecords;
import com.cn.exclusiveGirlfriend.pojo.OperationrecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationrecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    long countByExample(OperationrecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int deleteByExample(OperationrecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int insert(Operationrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int insertSelective(Operationrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    List<Operationrecords> selectByExample(OperationrecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    Operationrecords selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Operationrecords record, @Param("example") OperationrecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Operationrecords record, @Param("example") OperationrecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Operationrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecords
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Operationrecords record);
}