package com.cn.exclusiveGirlfriend.mapper;

import com.cn.exclusiveGirlfriend.dataBean.SchoolgirlDataBean;
import com.cn.exclusiveGirlfriend.pojo.Schoolgirl;
import com.cn.exclusiveGirlfriend.pojo.SchoolgirlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolgirlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    long countByExample(SchoolgirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolgirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int insert(Schoolgirl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int insertSelective(Schoolgirl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    List<Schoolgirl> selectByExample(SchoolgirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    Schoolgirl selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Schoolgirl record, @Param("example") SchoolgirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Schoolgirl record, @Param("example") SchoolgirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Schoolgirl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolgirl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Schoolgirl record);
    /**
    *@Description: 分页模糊查询数据(女生详情)
    *@Param: [schoolgirlDataBean]
    *@return: java.util.List<com.cn.exclusiveGirlfriend.pojo.Schoolgirl>
    *@Author: Yang Fang Hong
    *@date: 2020/9/24
    */
    List<Schoolgirl> selectSchoolgirlAll(SchoolgirlDataBean schoolgirlDataBean);
}